torso_length: 30.0
sleeve_length: 50.0
torso_circumference: 108.0
sleeve_circumference_bicep: 50.0
sleeve_circumference_wrist: 32.0
yoke_depth: 26.0
collar_circumference: 70.0
sleeve_rib_length: 10.0
torso_rib_length: 6.0
collar_rib_length: 4.0
collar_back_rise: 4.0
